# This is a basic workflow to help you get started with Actions

name: UnZip

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unzip:
    # The type of runner that the job will run on
    runs-on: windows-latest

      # Runs a single command using the runners shell
      - name: unzip
        run: 7z x hurr-durr/hurr-durr.zip
